-- Clear existing branches and insert correct ones
DELETE FROM retail_branches;

-- SHOPRITE (30 branches)
INSERT INTO retail_branches (id, store, name, is_liquor) VALUES
(uuid_generate_v4(), 'Shoprite', 'Shoprite Divundu', false),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Gobabis', false),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Goreangab', false),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Gwashamba', false),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Grootfontein', false),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Independence', false),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Katima Mulilo', false),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Katutura', false),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Keetmanshoop', false),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Khorixas', false),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Kuisebmond Mini', false),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Lafrenz', false),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Mariental', false),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Mondesa Mini', false),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Ohangwena Express', false),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Okahandja', false),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Ondangwa', false),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Oshakati', false),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Oshikango', false),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Otjiwarongo', false),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Outapi', false),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Oshana', false),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Oshifo', false),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Otjinene', false),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Rehoboth', false),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Rundu Galaxy', false),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Rundu Mall', false),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Swakopmund', false),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Tsumeb', false),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Walvis Bay', false),
-- SHOPRITE LIQUOR (19)
(uuid_generate_v4(), 'Shoprite', 'Shoprite Liquor Divundu', true),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Liquor Gobabis', true),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Liquor Katima Mulilo', true),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Liquor Katutura', true),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Liquor Keetmanshoop', true),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Liquor Lafrenz', true),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Liquor Maerua', true),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Liquor Mariental', true),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Liquor Mondesa Mini Shop', true),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Liquor Oshakati', true),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Liquor Oshikango', true),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Liquor Otjiwarongo', true),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Liquor Outapi', true),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Liquor Oshana', true),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Liquor Otjinene', true),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Liquor Okahandja', true),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Liquor Rehoboth', true),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Liquor Swakopmund', true),
(uuid_generate_v4(), 'Shoprite', 'Shoprite Liquor Walvis Bay', true),
-- CHECKERS (8)
(uuid_generate_v4(), 'Checkers', 'Checkers Dunes Mall Walvis Bay', false),
(uuid_generate_v4(), 'Checkers', 'Checkers Waterfront Swakopmund', false),
(uuid_generate_v4(), 'Checkers', 'Checkers Academia', false),
(uuid_generate_v4(), 'Checkers', 'Checkers Grove Mall', false),
(uuid_generate_v4(), 'Checkers', 'Checkers Gustav', false),
(uuid_generate_v4(), 'Checkers', 'Checkers Klein Windhoek', false),
(uuid_generate_v4(), 'Checkers', 'Checkers Maerua Mall', false),
(uuid_generate_v4(), 'Checkers', 'Checkers Wernhil', false),
-- CHECKERS LIQUOR (7)
(uuid_generate_v4(), 'Checkers', 'Checkers Liquor Dunes Mall Walvis Bay', true),
(uuid_generate_v4(), 'Checkers', 'Checkers Liquor Waterfront Swakopmund', true),
(uuid_generate_v4(), 'Checkers', 'Checkers Liquor Academia', true),
(uuid_generate_v4(), 'Checkers', 'Checkers Liquor Grove Mall', true),
(uuid_generate_v4(), 'Checkers', 'Checkers Liquor Maerua Mall', true),
(uuid_generate_v4(), 'Checkers', 'Checkers Liquor Gustav', true),
(uuid_generate_v4(), 'Checkers', 'Checkers Liquor Wernhil', true),
-- USAVE (26)
(uuid_generate_v4(), 'Usave', 'Usave Arandis', false),
(uuid_generate_v4(), 'Usave', 'Usave Aranos', false),
(uuid_generate_v4(), 'Usave', 'Usave Dorado Valley', false),
(uuid_generate_v4(), 'Usave', 'Usave Eenhana', false),
(uuid_generate_v4(), 'Usave', 'Usave Havanna', false),
(uuid_generate_v4(), 'Usave', 'Usave Henties Bay', false),
(uuid_generate_v4(), 'Usave', 'Usave Karasburg', false),
(uuid_generate_v4(), 'Usave', 'Usave Katutura', false),
(uuid_generate_v4(), 'Usave', 'Usave Katima Mulilo', false),
(uuid_generate_v4(), 'Usave', 'Usave Nkurenkuru', false),
(uuid_generate_v4(), 'Usave', 'Usave Okahandja', false),
(uuid_generate_v4(), 'Usave', 'Usave Okahao', false),
(uuid_generate_v4(), 'Usave', 'Usave Okakarara', false),
(uuid_generate_v4(), 'Usave', 'Usave Okalongo', false),
(uuid_generate_v4(), 'Usave', 'Usave Okauryangava', false),
(uuid_generate_v4(), 'Usave', 'Usave Omaruru', false),
(uuid_generate_v4(), 'Usave', 'Usave Omuthiya', false),
(uuid_generate_v4(), 'Usave', 'Usave Ondangwa', false),
(uuid_generate_v4(), 'Usave', 'Usave Ongenga', false),
(uuid_generate_v4(), 'Usave', 'Usave Opuwo', false),
(uuid_generate_v4(), 'Usave', 'Usave Oshakati Etango', false),
(uuid_generate_v4(), 'Usave', 'Usave Oshikuku', false),
(uuid_generate_v4(), 'Usave', 'Usave Rehoboth', false),
(uuid_generate_v4(), 'Usave', 'Usave Rosh Pinah', false),
(uuid_generate_v4(), 'Usave', 'Usave Tsandi', false),
(uuid_generate_v4(), 'Usave', 'Usave Mondesa', false),
-- USAVE LIQUOR (2)
(uuid_generate_v4(), 'Usave', 'Usave Liquor Soweto', true),
(uuid_generate_v4(), 'Usave', 'Usave Liquor Henties Bay', true);
