// Imported from LA Signs & Graphics.xlsx, sheet Job List 2025.
// This seeds only the duplicate production-sheet test page.
export const importedProductionRows = [
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "INVOICED",
    "date": "22/05",
    "company": "Roofmore Construction",
    "job": "Assorted Signs",
    "comments": "AWAITING LARGE SIGNS ARTWORK FROM CLIENT (SMALL SIGNS READY)",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "INVOICED",
    "date": "30/06",
    "company": "Safewear",
    "job": "Rally Car Branding",
    "comments": "TO COMPLETE CAR AFTER RALLY - NEEDS TO BE RESPRAYED",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "orange",
    "done": false,
    "status": "",
    "date": "16/09",
    "company": "Hafeni",
    "job": "Sublimated Mugs - Qty 6 Blank in Stock (NO ARTWORK)",
    "comments": "AWAITING NEXT ORDER",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "INVOICED / PAID - 29/10",
    "date": "30/10",
    "company": "PeeBoo Plumbing",
    "job": "Vehicle Branding - Qty 1",
    "comments": "03/11 - Car 1 done - Awaiting date for Car 2\n03/11 First Bakkie to Come For Branding",
    "feedback": "Second Bakkie is still being restored and will come at a later date - TBD",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "",
    "date": "12/12",
    "company": "Hardrock Earthworks Pylon",
    "job": "Swakopmund",
    "comments": "Coastal Couriers / 30/04 - Waiting installation date and spot\nDeadline 30/01/26",
    "feedback": "",
    "next_step": "",
    "due_date": "30/01/26",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "",
    "date": "11/02",
    "company": "SHOPRITE/CHECKERS Sashes",
    "job": "PRINTS QUEUED 10/03 @ 07H40",
    "comments": "",
    "feedback": "",
    "next_step": "PRINTS QUEUED 10/03 @ 07H40",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "01/04",
    "company": "NAMIBIA 4 LIFE",
    "job": "Frame with Stand & Poster",
    "comments": "LAYOUT SENT 09/04 @ 08H18 - FOLLOWED UP 13/04 - FOLLOWED UP 05 May 2026 @ 09H32",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "02/04",
    "company": "NGES (MOOLA BETTING)",
    "job": "2 Boxes for Modification",
    "comments": "4hrs Labour 10/04 + 6hrs Labour 13/04 + 1275x3100 Print & Lam for Terminals - AWAITING ON LAST INFO FROM PIKKIE",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "purple",
    "done": false,
    "status": "",
    "date": "24/06",
    "company": "UTOPIA",
    "job": "Site Visit for SIgnage",
    "comments": "WILVERT TO DO SITE VISIT, Wednesday, 24 June 2026 - WE WILL HAVE TO DO A SECOND SITE VISIT ONCE WE RECEIVE THE LIST OF WHAT STAYS & WHAT GOES + ARTWORK - LIZEL OUT OF TOWN THE 29/06 till 05/07\nLIZEL SENT 4 OF THE 12 WALLS ARTWORK 26/06 @ 09H32 (WHATSAPP) - WAITING FOR THE OTHER 8 :)",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "INVOICED",
    "date": "10/07",
    "company": "Excelsior Construction",
    "job": "(Anita WhatsApp) Stickers",
    "comments": "PRINTS QUEUED 13/07 @ 11H41\nWag vir stickers",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "red",
    "done": false,
    "status": "INVOICED",
    "date": "13/07",
    "company": "Emeco Scent",
    "job": "Assorted Dome Stickers",
    "comments": "TO EXPORT PRINTS ONCE PAYMENT IS RECEIVED",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "INVOICED/PAID 10/07",
    "date": "14/07",
    "company": "Quartz Construction",
    "job": "Site Board & Poles 1500x1200",
    "comments": "PRINT QUEUED 14/07 @ 17H11",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "red",
    "done": false,
    "status": "",
    "date": "15/07",
    "company": "HELPING BETS WITH IVECO / FAW PYLON",
    "job": "",
    "comments": "",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "INVOICED",
    "date": "16/07",
    "company": "Gymkhana Club Windhoek",
    "job": "Promo Vinyl Print & Lam Stickers 1800x500 - Qty 8",
    "comments": "PRINTS QUEUED 20/07 @ 11H00\nWag vir stickers",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "16/07",
    "company": "SHOPRITE DBAY COLLAB",
    "job": "ASSORTED PRINTS & WOBBLERS & MOBILES ETC",
    "comments": "PRINTS QUEUED 17/07 @ 07H30 - AWAITING MECHANICAL POSTERS ARTWORK (MATERIAL ORDERED 17/07 @ 09H00) - In production (17/07)",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "red",
    "done": false,
    "status": "TO EMAIL AMENDED JOB CARD ONCE STACKED & QTY AMENDED",
    "date": "17/07",
    "company": "Impact Manufacturing",
    "job": "Magnets with Print & Lam",
    "comments": "LAYOUTS SENT 21/07 @ 07H55 - AWAITING FEEDBACK / APPROVAL",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "INVOICED/PD",
    "date": "17/07",
    "company": "Melbic Car Rentals",
    "job": "Assorted Stickers",
    "comments": "PRINTD QUEUED 20/07 @ 10H05\nWag vir stickers",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "TO EMAIL JOB CARD",
    "date": "17/07",
    "company": "CHECKERS GENERIC DI",
    "job": "POSTERS & BUNTING BANNERS",
    "comments": "BUNTING BANNER PRINTS SENT TO VERTICAL GRAPHICS 17/07 @ 16H00 - POSTER PRINTS QUEUED 20/07 @ 10H00",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "INVOICED",
    "date": "20/07",
    "company": "Gymkhana Stabling Club Windhoek",
    "job": "Promo Print & Lam Stickers - Qty 6",
    "comments": "PRINTS QUEUED 20/07 @ 11H00\nWag vir stickers",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "",
    "date": "20/07",
    "company": "TShirts & More",
    "job": "Assorted DTF Prints",
    "comments": "PRINTS QUEUED 21/07 @ 11H32",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "",
    "date": "",
    "company": "CHECKERS LINES - MONTH END & LIQUOR",
    "job": "PRINTS QUEUED 21/07 @ 10H19 / ME IN PRODUCTION",
    "comments": "",
    "feedback": "",
    "next_step": "PRINTS QUEUED 21/07 @ 10H19 / ME IN PRODUCTION",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "",
    "date": "",
    "company": "USAVE POSTERS",
    "job": "PRINTS QUEUED 20/07 @ 15H34 / IN PRODUCTION",
    "comments": "",
    "feedback": "",
    "next_step": "PRINTS QUEUED 20/07 @ 15H34 / IN PRODUCTION",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "",
    "date": "",
    "company": "SHOPRITE LINES - MONTH END & LIQUOR",
    "job": "FIRST 2 SETS QUEUED 21/07 @ 16H32 -  LAST 2 SETS QUEUED 21/07 @ 18H32",
    "comments": "",
    "feedback": "",
    "next_step": "FIRST 2 SETS QUEUED 21/07 @ 16H32 -  LAST 2 SETS QUEUED 21/07 @ 18H32",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "red",
    "done": false,
    "status": "QU0571/PD17/07",
    "date": "",
    "company": "Auto Care - Triplicate books - PROCEED",
    "job": "TO RE-TYPE & DESIGN",
    "comments": "",
    "feedback": "",
    "next_step": "TO RE-TYPE & DESIGN",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "INVOICED",
    "date": "20/07",
    "company": "Probe Energy & Mining Namibia",
    "job": "Stickers",
    "comments": "PRINTS QUEUED 21/07 @ 12H19",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "red",
    "done": false,
    "status": "TO EMAIL JOB CARD",
    "date": "21/07",
    "company": "Vex-Men",
    "job": "Krips & Bottle Openers - TO SETUP ARTWORK",
    "comments": "TO SETUP ARTWORK & OPEN JOB CARD",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "red",
    "done": false,
    "status": "",
    "date": "21/07",
    "company": "Sanlam Allianz",
    "job": "Dbl SIded BC 50x90 - Likando David Mutwamezi - Qty 250",
    "comments": "APPPROVED 22/07 @ 11H33 - TO EXPORT FOR PRINTING & EMAIL TO CTRL-P\nGeorge Uukelo Approved the QUOTE on the 21/07 @ 14H57",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "TO EMAIL JOB CARD",
    "date": "21/07",
    "company": "Melbic Car Rentals",
    "job": "Numberplate Stickers",
    "comments": "PRINTS QUEUED 22/07 @ 10H19",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "",
    "date": "21/07",
    "company": "Purple Butterfly",
    "job": "Flammable Stickers 690x90 - Qty 9",
    "comments": "PRINTS QUEUED 21/07 @ 21H40\nCourier Otjiwarongo",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "21/07",
    "company": "Purple Butterfly",
    "job": "Magnets 420x420 - Qty 6",
    "comments": "TO SETUP ARTWORK FOR PRINTING\nCourier Otjiwarongo",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "yellow",
    "done": false,
    "status": "TO EMAIL QUOTE",
    "date": "22/07",
    "company": "Power Prima",
    "job": "Street Name & Building Signs",
    "comments": "TO QUOTE AFTER SITE VISIT 23/07 @ 09H00",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "yellow",
    "done": false,
    "status": "TO EMAIL QUOTE",
    "date": "22/07",
    "company": "Fast Fire Services",
    "job": "Assorted Photolum Safety Signs",
    "comments": "TO QUOTE",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "orange",
    "done": false,
    "status": "QUO0000582 - TO PAY N$1322.50 VAT INCL",
    "date": "22/07",
    "company": "PeeBoo Plumbing",
    "job": "Carry Canopy Branding",
    "comments": "TO EXPORT ARTWORK FOR PRINTING + EMAIL LAYOUT TO MICHELLE",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "red",
    "done": false,
    "status": "",
    "date": "02/04",
    "company": "ROLAND BIKE TANK PAD & GULF STICKER",
    "job": "COLOUR ISSUES",
    "comments": "COLOUR TESTS - REPRINT & DOME",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "orange",
    "done": false,
    "status": "",
    "date": "11/02",
    "company": "CHECKERS Sashes",
    "job": "only 76 x Turquois sashas",
    "comments": "COMPLETION DATE 6 MARCH 2026 (4 WEEKS PRODUCTION)",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "orange",
    "done": false,
    "status": "",
    "date": "17/07",
    "company": "Indongo Toyota New Cars Business Cards",
    "job": "Send 2 Solitaire Press",
    "comments": "",
    "feedback": "",
    "next_step": "Send 2 Solitaire Press",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "green",
    "done": false,
    "status": "INVOICED",
    "date": "04/08",
    "company": "Easy Tiger",
    "job": "Car branding",
    "comments": "Ready for application\nNO feedback...",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "orange",
    "done": false,
    "status": "",
    "date": "26/06",
    "company": "Urban Camp",
    "job": "Mariette Boat Stencil + signwriting",
    "comments": "Exported for printing",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "14/07",
    "company": "Adweb Africa ID Cards UV",
    "job": "QUOTE",
    "comments": "",
    "feedback": "",
    "next_step": "QUOTE",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "orange",
    "done": false,
    "status": "INVOICED",
    "date": "15/07",
    "company": "Marriette Open Range Marketing",
    "job": "October Fest",
    "comments": "Printing Done",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "green",
    "done": false,
    "status": "INVOICED/PO received",
    "date": "15/07",
    "company": "Indongo Toyota New Cars Business Cards",
    "job": "Send 2 Solitaire Press",
    "comments": "",
    "feedback": "",
    "next_step": "Send 2 Solitaire Press",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "15/07",
    "company": "Indongo Toyota Used Cars Business Cards",
    "job": "Waiting on P.O",
    "comments": "",
    "feedback": "",
    "next_step": "Waiting on P.O",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "orange",
    "done": false,
    "status": "",
    "date": "17/07",
    "company": "Indongo Toyota  Visfees Karre",
    "job": "Busy Design",
    "comments": "",
    "feedback": "",
    "next_step": "Busy Design",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "20/07",
    "company": "Indongon Toyota Tents",
    "job": "Design",
    "comments": "",
    "feedback": "",
    "next_step": "Design",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "orange",
    "done": false,
    "status": "",
    "date": "20/07",
    "company": "Winnie Koopman",
    "job": "Exported for printing",
    "comments": "Reprint Winnie",
    "feedback": "",
    "next_step": "Exported for printing",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "21/07",
    "company": "Indongo Toyota Mr Niikela HTS Signwriting",
    "job": "Measurements",
    "comments": "",
    "feedback": "",
    "next_step": "Measurements",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "none",
    "done": false,
    "status": "",
    "date": "21/07",
    "company": "Claudine MDF",
    "job": "Design",
    "comments": "",
    "feedback": "",
    "next_step": "Design",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "21/07",
    "company": "Anthonygoliath Investment CC",
    "job": "Approved, please proceed.",
    "comments": "",
    "feedback": "",
    "next_step": "Approved, please proceed.",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "21/07",
    "company": "Rezario E. Coetzee",
    "job": "backdrop",
    "comments": "",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "none",
    "done": false,
    "status": "",
    "date": "21/07",
    "company": "MOTH Centre,Moth stickers x25, Kongres 2026 x25 40x40mm Site visit reel",
    "job": "",
    "comments": "",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "yellow",
    "done": false,
    "status": "PAID 21/07",
    "date": "21/07",
    "company": "Auto Trader",
    "job": "PROCEED with contravision",
    "comments": "DESIGN SEND",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "none",
    "done": false,
    "status": "",
    "date": "22/07",
    "company": "Urban Camp Wall Branding",
    "job": "",
    "comments": "",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "none",
    "done": false,
    "status": "",
    "date": "22/07",
    "company": "JOKERS DAIL A MEAL",
    "job": "",
    "comments": "",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "none",
    "done": false,
    "status": "",
    "date": "",
    "company": "",
    "job": "",
    "comments": "",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "none",
    "done": false,
    "status": "",
    "date": "",
    "company": "",
    "job": "",
    "comments": "",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "none",
    "done": false,
    "status": "",
    "date": "",
    "company": "",
    "job": "",
    "comments": "",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "yellow",
    "done": false,
    "status": "INVOICED/PD 05/06",
    "date": "09/06",
    "company": "NNOC",
    "job": "Omaruru signage",
    "comments": "awaiting approval from client",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "11/06",
    "company": "JL Farming",
    "job": "Approved / waiting instructions from client",
    "comments": "",
    "feedback": "",
    "next_step": "Approved / waiting instructions from client",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "yellow",
    "done": false,
    "status": "INVOICED",
    "date": "26/06",
    "company": "Ekonofoods",
    "job": "Perfect Water",
    "comments": "Approved / waiting artwork from client",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "yellow",
    "done": false,
    "status": "INVOICED",
    "date": "30/06",
    "company": "Africa Commercial Vehicles",
    "job": "Iveco - Burney",
    "comments": "To Quote - Nicole",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "red",
    "done": false,
    "status": "INVOICED/PAID",
    "date": "07/07",
    "company": "Petro Enright",
    "job": "Installasie - 27 Julie",
    "comments": "",
    "feedback": "",
    "next_step": "Installasie - 27 Julie",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "black",
    "done": false,
    "status": "",
    "date": "09/07",
    "company": "NHRSA Certificates x23",
    "job": "To Invoice",
    "comments": "",
    "feedback": "",
    "next_step": "To Invoice",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "green",
    "done": false,
    "status": "INVOICED/PD",
    "date": "10/07",
    "company": "Touch of Style",
    "job": "Exit signs (Nampower)",
    "comments": "exported for Printing\nInstallation  22/07",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "none",
    "done": false,
    "status": "QUOTED / Proceed??",
    "date": "13/07",
    "company": "Haircraft",
    "job": "To Invoice",
    "comments": "Installation  28/07 9am",
    "feedback": "",
    "next_step": "To Invoice",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "yellow",
    "done": false,
    "status": "INVOICED",
    "date": "16/07",
    "company": "Impact",
    "job": "Feedmaster 2x Hilux / 1x Starlet",
    "comments": "Installation 20/07",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "black",
    "done": false,
    "status": "INVOICED/PAID 21/07",
    "date": "15/07",
    "company": "RAW Namibia",
    "job": "Flyers",
    "comments": "Outsource Impact Printing",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "none",
    "done": false,
    "status": "",
    "date": "15/07",
    "company": "Francois Snyders",
    "job": "Jeep",
    "comments": "design/layout",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "green",
    "done": false,
    "status": "INVOICED",
    "date": "20/07",
    "company": "Jokers",
    "job": "Skuifdeur Stickers",
    "comments": "exported for cutting",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "green",
    "done": false,
    "status": "INVOICED",
    "date": "17/07",
    "company": "Renov",
    "job": "Signage 1000x750mm",
    "comments": "exported for Printing",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "green",
    "done": false,
    "status": "INVOICED",
    "date": "17/07",
    "company": "Rabes Body Works Bus Cards, Lisence Discs",
    "job": "exported for Printing",
    "comments": "",
    "feedback": "",
    "next_step": "exported for Printing",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "none",
    "done": false,
    "status": "",
    "date": "17/07",
    "company": "Green Door Properties",
    "job": "Reprint",
    "comments": "",
    "feedback": "",
    "next_step": "Reprint",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "none",
    "done": false,
    "status": "",
    "date": "20/07",
    "company": "OshMed",
    "job": "Repair",
    "comments": "",
    "feedback": "",
    "next_step": "Repair",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "green",
    "done": false,
    "status": "INVOICED",
    "date": "20/07",
    "company": "Impact",
    "job": "Feedmaster Numberplates",
    "comments": "exported for Printing",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "green",
    "done": false,
    "status": "INVOICED/PD20/07",
    "date": "20/07",
    "company": "Binary City Signage",
    "job": "exported for Printing / Gabes Frame",
    "comments": "",
    "feedback": "",
    "next_step": "exported for Printing / Gabes Frame",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "green",
    "done": false,
    "status": "INVOICED",
    "date": "21/07",
    "company": "AGA Service Stickers x250",
    "job": "exported for Printing",
    "comments": "",
    "feedback": "",
    "next_step": "exported for Printing",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "red",
    "done": false,
    "status": "",
    "date": "21/07",
    "company": "Impact",
    "job": "Feedmaster - REDO applicated upside down",
    "comments": "REDO applicated upside down 22/07 EOD",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "21/07",
    "company": "JSB Sport Vinyl Stickers",
    "job": "To Quote",
    "comments": "",
    "feedback": "",
    "next_step": "To Quote",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "22/07",
    "company": "Elmien",
    "job": "Novecy",
    "comments": "To Quote",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "22/07",
    "company": "Tanja Mueller",
    "job": "To Quote",
    "comments": "",
    "feedback": "",
    "next_step": "To Quote",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "none",
    "done": false,
    "status": "",
    "date": "",
    "company": "",
    "job": "",
    "comments": "",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "none",
    "done": false,
    "status": "",
    "date": "",
    "company": "",
    "job": "",
    "comments": "",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "none",
    "done": false,
    "status": "",
    "date": "",
    "company": "",
    "job": "",
    "comments": "",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  }
]
