// Imported from LA Signs & Graphics (1).xlsx, sheet Job List 2025.
// This seeds the production-sheet page without duplicating blank spreadsheet rows.
export const importedProductionRows = [
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "INVOICED",
    "date": "22/05",
    "company": "Roofmore Construction",
    "job": "Assorted Signs",
    "comments": "AWAITING LARGE SIGNS ARTWORK FROM CLIENT (SMALL SIGNS READY)",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "INVOICED",
    "date": "30/06",
    "company": "Safewear",
    "job": "Rally Car Branding",
    "comments": "TO COMPLETE CAR AFTER RALLY - NEEDS TO BE RESPRAYED",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "16/09",
    "company": "Hafeni",
    "job": "Sublimated Mugs - Qty 6 Blank in Stock (NO ARTWORK)",
    "comments": "AWAITING NEXT ORDER",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "INVOICED / PAID - 29/10",
    "date": "30/10",
    "company": "PeeBoo Plumbing",
    "job": "Vehicle Branding - Qty 1",
    "comments": "03/11 - Car 1 done - Awaiting date for Car 2\n03/11 First Bakkie to Come For Branding",
    "feedback": "Second Bakkie is still being restored and will come at a later date - TBD",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "",
    "date": "12/12",
    "company": "Hardrock Earthworks Pylon",
    "job": "Swakopmund",
    "comments": "Coastal Couriers / 30/04 - Waiting installation date and spot\nDeadline 30/01/26",
    "feedback": "",
    "next_step": "",
    "due_date": "30/01/26",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "",
    "date": "11/02",
    "company": "SHOPRITE/CHECKERS Sashes",
    "job": "",
    "comments": "PRINTS QUEUED 10/03 @ 07H40",
    "feedback": "",
    "next_step": "PRINTS QUEUED 10/03 @ 07H40",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "01/04",
    "company": "NAMIBIA 4 LIFE",
    "job": "Frame with Stand & Poster",
    "comments": "LAYOUT SENT 09/04 @ 08H18 - FOLLOWED UP 13/04 - FOLLOWED UP 05 May 2026 @ 09H32",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "02/04",
    "company": "NGES (MOOLA BETTING)",
    "job": "2 Boxes for Modification",
    "comments": "4hrs Labour 10/04 + 6hrs Labour 13/04 + 1275x3100 Print & Lam for Terminals - AWAITING ON LAST INFO FROM PIKKIE",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "24/06",
    "company": "UTOPIA",
    "job": "Site Visit for SIgnage",
    "comments": "WILVERT TO DO ADDITIONAL MEASUREMENTS 23/07 - TO QUOTE\nLIZEL SENT 4 OF THE 12 WALLS ARTWORK 26/06 @ 09H32 (WHATSAPP) - WAITING FOR THE OTHER 8 :)",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "INVOICED",
    "date": "10/07",
    "company": "Excelsior Construction",
    "job": "(Anita WhatsApp) Stickers",
    "comments": "PRINTS QUEUED 13/07 @ 11H41\nWag vir stickers",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "yellow",
    "done": false,
    "status": "INVOICED",
    "date": "13/07",
    "company": "Emeco Scent",
    "job": "Assorted Dome Stickers",
    "comments": "TO EXPORT PRINTS ONCE PAYMENT IS RECEIVED\nWag vir payment",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "INVOICED/PAID 10/07",
    "date": "14/07",
    "company": "Quartz Construction",
    "job": "Site Board & Poles 1500x1200",
    "comments": "PRINT QUEUED 14/07 @ 17H11\n23/7 - Client wil weet wanneer kry hy sy bord",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "purple",
    "done": false,
    "status": "",
    "date": "15/07",
    "company": "HELPING BETS WITH IVECO / FAW PYLON",
    "job": "",
    "comments": "",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "16/07",
    "company": "SHOPRITE DBAY COLLAB",
    "job": "ASSORTED PRINTS & WOBBLERS & MOBILES ETC",
    "comments": "PRINTS QUEUED 17/07 @ 07H30 - AWAITING MECHANICAL POSTERS ARTWORK (MATERIAL ORDERED 17/07 @ 09H00) - In production (17/07)",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "INVOICED",
    "date": "17/07",
    "company": "Impact Manufacturing",
    "job": "Magnets with Print & Lam - QTY 55",
    "comments": "PRINTS QUEUED 22/07 @ 16H17",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "INVOICED/PD",
    "date": "17/07",
    "company": "Melbic Car Rentals",
    "job": "Assorted Stickers",
    "comments": "PRINTD QUEUED 20/07 @ 10H05",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "",
    "date": "",
    "company": "SHOPRITE LINES - MONTH END & LIQUOR",
    "job": "",
    "comments": "IN PRODUCTION - local branched delivered on 23/07",
    "feedback": "",
    "next_step": "IN PRODUCTION - local branched delivered on 23/07",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "yellow",
    "done": false,
    "status": "QU0571/PD17/07",
    "date": "21/07",
    "company": "Auto Care",
    "job": "Triplicate books - PROCEED",
    "comments": "TO RE-TYPE & DESIGN",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "INVOICED",
    "date": "21/07",
    "company": "Vex-Men",
    "job": "Krips 5LRG & 4 SML & Bottle Openers 5",
    "comments": "KRIPS CUTS QUEUED 23/07 @ 11H33 - BOTTLE OPENERS QUEUED 23/07 @ 13H06",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "",
    "date": "21/07",
    "company": "Sanlam Allianz",
    "job": "Dbl SIded BC 50x90 - Likando David Mutwamezi - Qty 250",
    "comments": "TO COLLECT\nGeorge Uukelo Approved the QUOTE on the 21/07 @ 14H57",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "INVOICED/PF",
    "date": "21/07",
    "company": "Purple Butterfly",
    "job": "Magnets 420x420 - Qty 6",
    "comments": "PRINTS QUEUED 21/07 @ 16H24\nCourier Hardap Otjiwarongo",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "INVOICED",
    "date": "22/07",
    "company": "PeeBoo Plumbing",
    "job": "Carry Canopy Branding",
    "comments": "PRINTS QUEUED 22/07 @ 16H17 / Application, Monday 27 July 2026",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "INVOICED",
    "date": "22/07",
    "company": "TFG",
    "job": "Jet Wernhil - 7 x Name Badges",
    "comments": "PRINTS QUEUED 23/07 @ 16H45",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "yellow",
    "done": false,
    "status": "INVOICED",
    "date": "22/07",
    "company": "Court Helicopters",
    "job": "Patches",
    "comments": "TO SETUP ARTWORK FOR APPROVAL",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "22/07",
    "company": "Build It Oshana",
    "job": "Screen Print Safety Signs 190x190",
    "comments": "TO SETUP ARTWORK FOR APPROVAL",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "",
    "date": "22/07",
    "company": "TShirts & More",
    "job": "Assorted DTF Prints for 23/07",
    "comments": "PRINTS QUEUED 23/07 @ 08H00",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "INVOICED",
    "date": "22/07",
    "company": "Sonja Etzold",
    "job": "Foam Cuts",
    "comments": "TO COLLECT\nDUE 24/7",
    "feedback": "",
    "next_step": "",
    "due_date": "24/7",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "23/07",
    "company": "Rian Kritz Motors",
    "job": "Design for car",
    "comments": "CONTACTED RIAN 23/07 @ 11H00 - LEFT A MESSAGE WITH THE RECEPTIONIST WHO ANSWERED HIS PHONE",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "INVOICED",
    "date": "23/07",
    "company": "Probe Energy & Mining Namibia",
    "job": "Stickers",
    "comments": "PRINTS QUEUED 23/07 @ 16H02",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "24/07",
    "company": "Risk Consultant Services",
    "job": "Dome Stickers 90x90 - Qty 20",
    "comments": "TO SEND LAYOUTS FOR APPROVAL",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "24/07",
    "company": "Risk Consultant Services",
    "job": "Print & Lam Stickers 330x250 - Qty 22",
    "comments": "TO SEND LAYOUTS FOR APPROVAL",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "green",
    "done": false,
    "status": "EMAIL FINAL JOB CARD",
    "date": "24/07",
    "company": "TShirts & More",
    "job": "DTF Prints ADDITIONAL + RUSH",
    "comments": "PRINTS QUEUED 24/07 @ 09H56",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Nicole",
    "highlight": "red",
    "done": false,
    "status": "",
    "date": "02/04",
    "company": "ROLAND BIKE TANK PAD & GULF STICKER",
    "job": "COLOUR ISSUES",
    "comments": "COLOUR TESTS - REPRINT & DOME",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Damion",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "22/07",
    "company": "VexMen Trading CC",
    "job": "Samples Exported for Bottle Opener",
    "comments": "FIBRE LASER FILE QUEUED ON 22/07 @ 15H37",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Damion",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "22/07",
    "company": "Sonja Etzold",
    "job": "25mm & 10mm Foam Cuts",
    "comments": "LASER FILE QUEUED ON 22/07 @ 16H55\nDUE 24/7",
    "feedback": "",
    "next_step": "",
    "due_date": "24/7",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Damion",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "22/07",
    "company": "TShirts & More",
    "job": "Assorted DTF Prints",
    "comments": "PRINTS QUEUED 23/07 @ 08H00",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Damion",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "23/07",
    "company": "VexMen Trading CC",
    "job": "(5 x Lrg Krips) (4 x Sml Crips )",
    "comments": "FIBRE LASER FILE QUEUED 23/07 @ 11H33",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Damion",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "23/07",
    "company": "VexMen Trading CC",
    "job": "(50 x Bottle Opener)",
    "comments": "BOTTLE OPENERS RE-QUEUED 23/07 @ 15H36",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Damion",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "23/07",
    "company": "Jet Wernhil",
    "job": "UV Printed Rowmark Badges - SILVER ROWMARK CUTS",
    "comments": "LASER FILES QUEUED 23/07 @ 16H40",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Damion",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "23/07",
    "company": "Jet Wernhil",
    "job": "UV Printed Rowmark Badges - UV PRINTS",
    "comments": "UV PRINTS QUEUED 23/07 @ 16H40",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Outsourcing",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "11/02",
    "company": "CHECKERS Sashes",
    "job": "only 76 x Turquois sashas",
    "comments": "COMPLETION DATE 6 MARCH 2026 (4 WEEKS PRODUCTION)",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Outsourcing",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "17/07",
    "company": "Indongo Toyota New Cars Business Cards",
    "job": "",
    "comments": "Send 2 Solitaire Press",
    "feedback": "",
    "next_step": "Send 2 Solitaire Press",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Outsourcing",
    "highlight": "none",
    "done": false,
    "status": "",
    "date": "",
    "company": "",
    "job": "",
    "comments": "COLLECTED",
    "feedback": "",
    "next_step": "COLLECTED",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "green",
    "done": false,
    "status": "INVOICED",
    "date": "04/08",
    "company": "Easy Tiger",
    "job": "Car branding",
    "comments": "Ready for application\nNO feedback...",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "green",
    "done": false,
    "status": "",
    "date": "",
    "company": "JSB - CREDIT 2545.95 EXCL VAT",
    "job": "",
    "comments": "",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "26/06",
    "company": "Urban Camp",
    "job": "Mariette Boat Stencil + signwriting",
    "comments": "1st week in Aug",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "14/07",
    "company": "Adweb Africa ID Cards UV",
    "job": "",
    "comments": "QUOTE",
    "feedback": "",
    "next_step": "QUOTE",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "green",
    "done": false,
    "status": "INVOICED/PO received",
    "date": "15/07",
    "company": "Indongo Toyota New Cars Business Cards",
    "job": "",
    "comments": "Send 2 Solitaire Press",
    "feedback": "",
    "next_step": "Send 2 Solitaire Press",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "15/07",
    "company": "Indongo Toyota Used Cars Business Cards",
    "job": "",
    "comments": "Waiting on P.O",
    "feedback": "",
    "next_step": "Waiting on P.O",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "17/07",
    "company": "Indongo Toyota Visfees Karre",
    "job": "",
    "comments": "Busy Design",
    "feedback": "",
    "next_step": "Busy Design",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "20/07",
    "company": "Indongon Toyota Tents",
    "job": "",
    "comments": "Design",
    "feedback": "",
    "next_step": "Design",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "21/07",
    "company": "Indongo Toyota Mr Niikela HTS Signwriting",
    "job": "",
    "comments": "Design Send",
    "feedback": "",
    "next_step": "Design Send",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "yellow",
    "done": false,
    "status": "INVOICED",
    "date": "21/07",
    "company": "Anthonygoliath Investment CC",
    "job": "",
    "comments": "Approved, please proceed.",
    "feedback": "",
    "next_step": "Approved, please proceed.",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "21/07",
    "company": "MOTH Centre,Moth stickers x25, Kongres 2026 x25 40x40mm Site visit reel",
    "job": "",
    "comments": "Monday 10:00 081 427 4625\nCalled no answer",
    "feedback": "",
    "next_step": "Monday 10:00 081 427 4625",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "yellow",
    "done": false,
    "status": "INVOICED/PAID 21/07",
    "date": "21/07",
    "company": "Auto Trader",
    "job": "PROCEED with contravision",
    "comments": "Monday",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "22/07",
    "company": "Urban Camp Wall Branding",
    "job": "",
    "comments": "Quote",
    "feedback": "",
    "next_step": "Quote",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "yellow",
    "done": false,
    "status": "23/07 - J/card asb?",
    "date": "22/07",
    "company": "JOKERS DAIL A MEAL",
    "job": "Bike box branding",
    "comments": "x10\nx1 bike geplak 22/7",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "23/07",
    "company": "Matthias Transworld Cargo, 0812166131 dankie",
    "job": "",
    "comments": "site visit - Wilvert to arrange with Matthias",
    "feedback": "",
    "next_step": "site visit - Wilvert to arrange with Matthias",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "green",
    "done": false,
    "status": "CASH payment",
    "date": "23/07",
    "company": "Wayne x2 ZA stickers",
    "job": "",
    "comments": "Done\nWag vir stickers",
    "feedback": "",
    "next_step": "Done",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "23/07",
    "company": "Indongo Toyota HTS wall Design",
    "job": "",
    "comments": "Design send",
    "feedback": "",
    "next_step": "Design send",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "23/07",
    "company": "River Lodge Quote",
    "job": "",
    "comments": "Quote",
    "feedback": "",
    "next_step": "Quote",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "green",
    "done": false,
    "status": "",
    "date": "23/07",
    "company": "Urban Camp Security House",
    "job": "",
    "comments": "Paid",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "24/07",
    "company": "WCH",
    "job": "",
    "comments": "Sien email",
    "feedback": "",
    "next_step": "Sien email",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "yellow",
    "done": false,
    "status": "INVOICED",
    "date": "24/07",
    "company": "Claudine3 12mm MDF",
    "job": "",
    "comments": "Approved",
    "feedback": "",
    "next_step": "Approved",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "yellow",
    "done": false,
    "status": "INVOCIED/PD 24/07",
    "date": "24/07",
    "company": "Briljante Breintjies",
    "job": "Medals - APPROVED",
    "comments": "",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "green",
    "done": false,
    "status": "",
    "date": "24/07",
    "company": "Hilton Hotel Frost",
    "job": "",
    "comments": "",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "24/07",
    "company": "Meyer Optometrist Arne Frost",
    "job": "",
    "comments": "Exported for cutting",
    "feedback": "",
    "next_step": "Exported for cutting",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Geraldo",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "24/07",
    "company": "Medical Imaging Brush",
    "job": "",
    "comments": "Exported for cutting",
    "feedback": "",
    "next_step": "Exported for cutting",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "yellow",
    "done": false,
    "status": "INVOICED/PD 05/06",
    "date": "09/06",
    "company": "NNOC",
    "job": "Omaruru signage",
    "comments": "awaiting approval from client",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "11/06",
    "company": "JL Farming",
    "job": "",
    "comments": "Approved / waiting instructions from client",
    "feedback": "",
    "next_step": "Approved / waiting instructions from client",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "yellow",
    "done": false,
    "status": "INVOICED",
    "date": "26/06",
    "company": "Ekonofoods",
    "job": "Perfect Water",
    "comments": "Approved / waiting artwork from client",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "red",
    "done": false,
    "status": "INVOICED",
    "date": "30/06",
    "company": "Africa Commercial Vehicles",
    "job": "Iveco - Burney",
    "comments": "To Quote - Nicole",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "red",
    "done": false,
    "status": "INVOICED/PAID",
    "date": "07/07",
    "company": "Petro Enright",
    "job": "",
    "comments": "Installasie - 27 Julie",
    "feedback": "",
    "next_step": "Installasie - 27 Julie",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "black",
    "done": false,
    "status": "",
    "date": "09/07",
    "company": "NHRSA Certificates x23",
    "job": "",
    "comments": "To Invoice",
    "feedback": "",
    "next_step": "To Invoice",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "yellow",
    "done": false,
    "status": "INVOICED/PD",
    "date": "10/07",
    "company": "Touch of Style",
    "job": "Exit signs (Nampower)",
    "comments": "client to confirm installation date / 23/07 - 2nd week of August",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "green",
    "done": false,
    "status": "INVOICED",
    "date": "13/07",
    "company": "Haircraft",
    "job": "",
    "comments": "Installation 28/07 9am / Ctrl-P BCards & Vouchers",
    "feedback": "",
    "next_step": "Installation 28/07 9am / Ctrl-P BCards & Vouchers",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "red",
    "done": false,
    "status": "",
    "date": "15/07",
    "company": "The Namibia Safari",
    "job": "Jeep",
    "comments": "Awaiting feedback from Client",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "green",
    "done": false,
    "status": "INVOICED",
    "date": "20/07",
    "company": "Jokers",
    "job": "Skuifdeur Stickers",
    "comments": "exported for cutting",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "green",
    "done": false,
    "status": "INVOICED",
    "date": "17/07",
    "company": "Renov",
    "job": "Signage 1000x750mm",
    "comments": "exported for Printing",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "none",
    "done": false,
    "status": "",
    "date": "17/07",
    "company": "Green Door Properties",
    "job": "",
    "comments": "Reprint / client to email artwork",
    "feedback": "",
    "next_step": "Reprint / client to email artwork",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "none",
    "done": false,
    "status": "",
    "date": "20/07",
    "company": "OshMed",
    "job": "",
    "comments": "24/07/2026",
    "feedback": "",
    "next_step": "24/07/2026",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "green",
    "done": false,
    "status": "INVOICED",
    "date": "20/07",
    "company": "Impact",
    "job": "Feedmaster Numberplates",
    "comments": "exported for Printing",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "green",
    "done": false,
    "status": "INVOICED/PD20/07",
    "date": "20/07",
    "company": "Binary City Signage",
    "job": "",
    "comments": "exported for Printing / Gabes Frame",
    "feedback": "",
    "next_step": "exported for Printing / Gabes Frame",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "green",
    "done": false,
    "status": "",
    "date": "23/07",
    "company": "Excelsior",
    "job": "Stickers Short",
    "comments": "exported for Printing",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "23/07",
    "company": "Beauty by Louiza",
    "job": "",
    "comments": "awaiting approval from client",
    "feedback": "",
    "next_step": "awaiting approval from client",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "yellow",
    "done": false,
    "status": "INVOICED / PD",
    "date": "23/07",
    "company": "Moslabon Bonsmaras",
    "job": "",
    "comments": "awaiting approval from client",
    "feedback": "",
    "next_step": "awaiting approval from client",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "green",
    "done": false,
    "status": "INVOICED",
    "date": "23/07",
    "company": "Impact",
    "job": "Ford Ranger Wrap",
    "comments": "exported for Printing",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "24/07",
    "company": "Farm Okanjesu Trophies",
    "job": "Erisna",
    "comments": "awaiting artwork from client\nDue 31/07",
    "feedback": "",
    "next_step": "",
    "due_date": "31/07",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "none",
    "done": false,
    "status": "",
    "date": "24/07",
    "company": "Torga",
    "job": "Goreangab Mall",
    "comments": "Wilvert - Extruded \"D\"",
    "feedback": "",
    "next_step": "",
    "due_date": "",
    "link_type": "",
    "link_number": "",
    "row_height": null
  },
  {
    "worker": "Bets-Mari",
    "highlight": "yellow",
    "done": false,
    "status": "",
    "date": "24/07",
    "company": "Impact",
    "job": "RE Supplies Promo Prints",
    "comments": "awaiting artwork from client\nDue 29/07 9am",
    "feedback": "",
    "next_step": "",
    "due_date": "29/07",
    "link_type": "",
    "link_number": "",
    "row_height": null
  }
]
